name: Build Release

on:
  push:
    tags:
      - "v*" # Matches tags starting with 'v'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23

    - name: Install dependencies
      run: go mod tidy

    - name: Install dependencies for Fyne
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev
      if: runner.os == 'Linux'

    - name: Install dependencies for Fyne on macOS
      run: |
        brew install gcc
      if: runner.os == 'macOS'

    - name: Install dependencies for Fyne on Windows
      run: |
        choco install mingw
      if: runner.os == 'Windows'

    - name: Build for macOS
      run: GOOS=darwin GOARCH=amd64 go build -o rn-builder-macos

    - name: Build for Windows
      run: GOOS=windows GOARCH=amd64 go build -o rn-builder-windows.exe

    - name: Build for Linux
      run: GOOS=linux GOARCH=amd64 go build -o rn-builder-linux

    - name: Archive builds
      run: |
        tar -czvf rn-builder-macos.tar.gz rn-builder-macos
        tar -czvf rn-builder-windows.tar.gz rn-builder-windows.exe
        tar -czvf rn-builder-linux.tar.gz rn-builder-linux

    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: rn-builder-artifacts
        path: |
          rn-builder-macos.tar.gz
          rn-builder-windows.tar.gz
          rn-builder-linux.tar.gz